# This action.yml name is compulsory as this name is centric to defining actions only
# and this file name must be there whenever we are creating our action. For composite
# actions this is the only file needed but for javascript and docker based custom 
# actions we need more files.

name: 'Get & Cached Dependencies'
description: 'Get the dependencies(via npm) and Cached them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache is used or not.'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
        echo "cache='${{ inputs.caching }}'">>$GITHUB_OUTPUT
      shell: bash